export default [
  {
    name: 'javascript',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  },
  { name: 'html', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML' },
  { name: 'css', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS' },
  { name: 'typescript', url: 'https://www.typescriptlang.org/' },
  { name: 'vue', url: 'https://cn.vuejs.org/' },
  { name: 'react', url: 'https://react.dev/' },
  { name: 'nextjs', url: 'https://nextjs.org/' },
  { name: 'sass', url: 'https://sass-lang.com/' },
  { name: 'tailwindcss', url: 'https://tailwindcss.com/' },
  { name: 'electron', url: 'https://www.electronjs.org/' },
  { name: 'markdown', url: 'https://www.markdownguide.org/' },
  { name: 'pinia', url: 'https://pinia.vuejs.org/' },
  { name: 'vite', url: 'https://vitejs.dev/' },
  { name: 'webpack', url: 'https://webpack.js.org/' },
  { name: 'babel', url: 'https://babeljs.io/' },
  { name: 'rollupjs', url: 'https://rollupjs.org/' },
  { name: 'vitepress', url: 'https://vitepress.dev/' },
  { name: 'vitest', url: 'https://vitest.dev/' },
  { name: 'mapbox', url: 'https://www.mapbox.com/' },
  { name: 'git', url: 'https://git-scm.com/' },
  { name: 'github', url: 'https://github.com/' },
  { name: 'npm', url: 'https://www.npmjs.com/' },
  { name: 'pnpm', url: 'https://pnpm.io/' },
  { name: 'nodejs', url: 'https://nodejs.org/' },
  { name: 'express', url: 'https://expressjs.com/' },
  { name: 'nestjs', url: 'https://nestjs.com/' },
  { name: 'mysql', url: 'https://www.mysql.com/' },
  { name: 'redis', url: 'https://redis.io/' },
  { name: 'docker', url: 'https://www.docker.com/' },
  { name: 'linux', url: 'https://www.kernel.org/' },
  { name: 'nginx', url: 'https://nginx.org/' },
  { name: 'python', url: 'https://www.python.org/' },
];
