packages:
  - 'docs/*'

catalogs:
  type:
    '@types/node': ^24.0.0
  style:
    sass: ^1.89.2
  build:
    vite: ^6.3.5
    vitepress: 2.0.0-alpha.4
  plugin:
    vite-plugin-vitepress-auto-sidebar: ^1.7.1
  lib:
    element-plus: ^2.10.1
    vue: ^3.5.16
  util:
    gray-matter: ^4.0.3
    moment: ^2.30.1
  icon:
    '@element-plus/icons-vue': ^2.3.1
  theme:
    vitepress-theme-website: ^1.0.8
